apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    email: {{ CLOUDFLARE_USER_EMAIL }}
    privateKeySecretRef:
      name: letsencrypt-dns-staging
    solvers:
    - dns01:
        cloudflare:
          email: {{ CLOUDFLARE_USER_EMAIL }}
          apiKeySecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    email: {{ CLOUDFLARE_USER_EMAIL }}
    privateKeySecretRef:
      name: letsencrypt-dns-prod
    solvers:
    - dns01:
        cloudflare:
          email: {{ CLOUDFLARE_USER_EMAIL }}
          apiKeySecretRef:
            name: cloudflare-api-token-secret
            key: api-token